### ISSUE TITLE
Only working from local host?

### ISSUE THREAD

**Issue by LucyWhitmore** [rivasd/jsPsychHardware#1]
My issue seems to be that my code communicates correctly with the extension (i.e. the extension recognizes that jsPsych is loaded into the page, as determined by the extension icon lighting up) when I load the page from webstorm, which uses a local host server. When I try to load the same file directly from my desktop, without a local host, the icon remains gray. Would the only solution here be to only use a local host instead of opening the file from my desktop, or is there something else that may be happening here? Any suggestions (or corrections) are appreciated! Many thanks.

**Comment by rivasd** [comment]
It seems that Google has [hidden in its documentation](https://developer.chrome.com/extensions/match_patterns) that extensions do not automatically have access to pages opened with `file://` scheme. In chrome, You will need to go to settings -> More tools -> Extensions ->click Details on the jsPsychHardware card -> **Allow access to file URLs**

Wish this was more explicitly told to the user!

**Comment by LucyWhitmore** [comment]
Wonderful, thank you so much!

**Comment by LucyWhitmore** [comment]
Hi Daniel,

Thanks so much again for all your help so far! We ran into one more weird
issue that I was hoping you may have some insight on. Basically, we're
trying to connect to a parallel port, but it seems that the extension is
only recognizing serial ports/using serial as the default. When we enter
the hex number for the parallel port and click the power icon, the
resulting message in the console says 'code: serial' and 'ports: array(2)',
which when expanded is an array containing the names of the two serial
ports. I attached a screenshot below, if that's helpful. We'd greatly
appreciate any clarification that you may be able to offer as to how to
resolve the problem. Thanks again!


Best,
Lucy

**Comment by LucyWhitmore** [comment]
Hi Daniel,

I just wanted to follow up on this, as well as offer some additional
information. Per a suggestion from Josh de Leeuw on the jspsych google
group, we also tried reverting to a previous version of the program. That
didn't seem to work, nor did trying to use a laptop (in case the difference
was having the parallel port on the motherboard versus not). Any further
advice would be appreciated, as would any information about the conditions
under which you've gotten the program to work correctly, so that we can try
and replicate those as much as possible.

Thanks again,
Lucy Whitmore
