### ISSUE TITLE
Extension connecting to serial instead of parallel?

### ISSUE THREAD

**Issue by LucyWhitmore** [rivasd/jsPsychHardware#2]
Hi,

I seem to be having a problem with the extension trying to automatically connect to a serial port (which is unused) instead of the parallel port that goes to our BioSemi acquisition system. After typing in the parallel port hex number and clicking the power icon, the brain icon turns green, but when looking at the console, it says that the serial port is connected, not the parallel port. After reverting to the older version of the chromeparallel program, the program no longer automatically connects to the serial ports, but will not connect to the parallel port, and the power icon next to the serial port flashes/pulses. I'm not sure of what's happening there, but any advice is much appreciated!

**Comment by frankgasking** [comment]
Hi Lucy,  did you manage to get this resolved in the end?

I am currently stuck at the exact same point.  Parallel port is firing triggers from other software,  but just not from jsPsychHardware.

**Comment by LucyWhitmore** [comment]
Hi Frank,

I did manage to get it resolved! I don't remember what the fix was for this exact bit of the problem, but I'll try to give an overview of what I remember, and hopefully something there helps. 
1) Manually install an older version of the extension to chrome. If I remember correctly, I just downloaded a version that didn't have a serial port. 
2) There may be a code/key in the extension files that needs to list the current version number/a code indicating what version or device you're using, double check that (I'm sorry I can't be more specific about that, basically just double check that all numbers/versions/etc line up everywhere in the code for the extension, and what you have in your chrome menu/settings. (I think this may be where your problem is, if you've already reverted to an old version)
3) Make sure the chrome extension is actually turned on (simple, but I definitely missed this at one point)
4) At least in the version that I was working with, clicking the brain icon in chrome always made it turn green, regardless of if it was working. Keep an eye on that, you have to make sure to click the brain icon, then click access hardware in order for things to work.

I hope something in there helps!

**Comment by frankgasking** [comment]
Hi Lucy,

Many thanks for getting back to me and for your help.

I tried installing an older version of the Chrome extension (Both 0.3 and 0.2), but unfortunately the icon remained red when putting in the parallel address.   For your point 2),  I think this was "allowed-origins" and the extension ID? (https://stackoverflow.com/questions/20216224/chrome-native-messaging-error-access-to-the-specified-native-messaging-host-i) .   Unfortunately this was for an older version of Chrome, and I couldn't find the replacement for this.

My issue seems to be with the above permissions - and the other errors i'm getting in the background which is preventing it from connecting:

![error](https://user-images.githubusercontent.com/2048377/64861036-dc061c00-d626-11e9-88af-df64776bf1d7.PNG)

Not sure if you had anything similar to this?
