### ISSUE TITLE
Byte values on serial ports

### ISSUE THREAD

**Issue by raj925** [rivasd/jsPsychHardware#4]
@rivasd I have been working on getting some triggers sent on the USB trigger interface for BIOSEMI. I realised it is recognised by the computer as a serial port. I am able to send triggers, but am not seeing them reflected in BIOSEMI. The current solution you have for sending triggers only allows string values on serial ports, but you say in the parallel port section that this is used for BIOSEMI, but this does not appear to be the case if the trigger hardware for BIOSEMI uses a serial port. What's more, BIOSEMI only takes byte values for timing reasons, but this only allows string values to be sent on serial ports. If this extension has been used before for BIOSEMI, how do you resolve this discrepancy? Thanks!

**Comment by raj925** [comment]
@rivasd

**Comment by rivasd** [comment]
Hi!

In our lab, we never have used the USB trigger interface, instead using the old fashioned parallel port. This means I have never tested or developed this tool with such hardware. I have only tested sending such serial commands via USB to an arduino and confirmed it received the corresponding string. Unfortunately, I do not have time to add this feature, but you are more than welcome to adapt my code! :)

Cheers,

**Comment by raj925** [comment]
Hello,

Thanks for your reply! That is as I suspected. I might then try to see if I can get sending bytes working by adapting the code. I'll let you know how I get on! Can you tell me where in your repository you handle the sending of information on a serial port?

Thanks!

**Comment by rivasd** [comment]
As explained on the README, the actual interfacing is done by an accompanying native c++ program https://github.com/rivasd/chromeparallel. This chrome extension assumes that program exists and is properly installed and simply passes json messages to it. The native program uses very low level system calls and could be probably be improved a lot by someone that actually knows c++ and the windows API, but it has the advantage of a very small footprint vs the usual solutions that use a web server listening on ``localhost``. I used Visual Studio Community edition 2015 to develop it and the repo should be compatible with it
